inherit_from: .rubocop_todo.yml

# This basically enshrines existing intentional styles

AllCops:
  TargetRubyVersion: 3.2.2

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
