=begin
#Payment Rails API

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.30.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PaymentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsApi' do
    it 'should create an instact of PaymentsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentsApi)
    end
  end

  # unit tests for query
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page page number default 1
  # @option opts [Integer] :page_size page size default 100
  # @option opts [String] :start_date filter recipients list by creation date from start date format YYYY-MM-DD
  # @option opts [String] :end_date filter recipients list by creation date to end date format YYYY-MM-DD
  # @option opts [String] :status filter recipients list by status
  # @option opts [String] :country filter by 2 letter country code
  # @option opts [String] :recipient filter by recipient ID R-XXXXXXXXXXXXXXXX
  # @option opts [String] :source_currency filter by source currency 3 letters ISO code
  # @option opts [String] :target_currency filter by target currency 3 letters ISO code
  # @return [InlineResponse2001]
  describe 'query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_payments_payment_id_get
  # 
  # 
  # @param payment_id P-XXXXXXXXXXXXXXXX
  # @param [Hash] opts the optional parameters
  # @return [PaymentOut]
  describe 'v1_payments_payment_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
